AppBundle\Entity\Product:
    type: entity
    table: products
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        quantity:
            type: integer
        price:
            type: decimal
            precision: 10
            scale: 2
        user_id:
            type: integer
    manyToOne:
        user:
            targetEntity: User
            inversedBy: products
            joinColumn:
                name: user_id
                referencedColumnName: id