AppBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        login:
            type: string
            length: 255
        password:
            type: string
            length: 255
    oneToMany:
        items:
            targetEntity: Product
            mappedBy: user